version: '3.9'

services:
  penny_trader_ripple:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    volumes:
      - ./app:/home/jovyan/app
    #command: tail -F anything
    environment:
      - currency='RIPPLE'
      - coin_balance_ticker='XXRP'
      - kraken_trading_pair='XRPXBT'
      - kraken_price_volume_result_trading_pair='XXRPXXBT'
      - poloniex_trading_pair='XRP_BTC'
      - bittrex_trading_pair='XRP-BTC'
      - kraken_discount_to_average_bid=0.0125
      - kraken_BTC_minimum_balance=0.05
      - kraken_BTC_order_size=0.05
      - kraken_minimum_coin_order_size=8
      - kraken_premium_to_average_ask=0.0035
      - public_key=${ripple_public_key}
      - private_key=${ripple_private_key}